import type { 
  UserProfile, 
  BienList, 
  BienDetail, 
  DemandeVisite, 
  Visite, 
  ChatRoom, 
  Message, 
  Notification,
  RapportVisite,
  PaginatedResponse 
} from '@shared/schema';

const mockUsers: UserProfile[] = [
  {
    id: 1,
    username: 'jean.dupont',
    email: 'jean.dupont@email.com',
    first_name: 'Jean',
    last_name: 'Dupont',
    role: 'client',
    role_display: 'Client',
    phone: '+243 812 345 678',
    date_joined: '2024-01-15T10:00:00Z',
    last_login: '2024-12-05T08:30:00Z'
  },
  {
    id: 2,
    username: 'marie.kambele',
    email: 'marie.kambele@email.com',
    first_name: 'Marie',
    last_name: 'Kambele',
    role: 'proprietaire',
    role_display: 'Propriétaire',
    phone: '+243 998 765 432',
    date_joined: '2024-02-20T10:00:00Z',
    last_login: '2024-12-04T14:20:00Z'
  },
  {
    id: 3,
    username: 'paul.mutombo',
    email: 'paul.mutombo@email.com',
    first_name: 'Paul',
    last_name: 'Mutombo',
    role: 'commissionnaire',
    role_display: 'Commissionnaire',
    phone: '+243 815 555 123',
    date_joined: '2024-03-10T10:00:00Z',
    last_login: '2024-12-05T09:00:00Z'
  },
  {
    id: 4,
    username: 'alice.lumumba',
    email: 'alice.lumumba@email.com',
    first_name: 'Alice',
    last_name: 'Lumumba',
    role: 'agent',
    role_display: 'Agent',
    phone: '+243 810 000 111',
    date_joined: '2024-04-05T10:00:00Z',
    last_login: '2024-12-05T07:45:00Z'
  },
  {
    id: 5,
    username: 'david.tshisekedi',
    email: 'david.tshisekedi@email.com',
    first_name: 'David',
    last_name: 'Tshisekedi',
    role: 'agent',
    role_display: 'Agent',
    phone: '+243 820 333 444',
    date_joined: '2024-05-10T10:00:00Z',
    last_login: '2024-12-04T16:30:00Z'
  }
];

const mockBiens: BienDetail[] = [
  {
    id: 1,
    titre: 'Villa moderne avec piscine à Gombe',
    description: 'Magnifique villa de 5 chambres avec piscine privée, jardin aménagé et garage pour 3 voitures. Située dans le quartier résidentiel calme de Gombe, cette propriété offre un cadre de vie exceptionnel. Finitions haut de gamme, cuisine équipée, climatisation centrale.',
    type_bien: 'villa',
    type_bien_display: 'Villa',
    prix_mensuel: '5000',
    devise: "USD" as const,
    garantie: '10000',
    superficie: '450',
    nombre_chambres: 5,
    nombre_salles_bain: 4,
    nombre_pieces: 12,
    ville: 'Kinshasa',
    quartier: 'Gombe',
    commune: 'Gombe',
    adresse: '123 Avenue du Commerce',
    latitude: '-4.3055',
    longitude: '15.3136',
    statut_validation: 'valide',
    statut_validation_display: 'Validé',
    statut_location: 'disponible',
    statut_location_display: 'Disponible',
    proprietaire: mockUsers[1],
    eau_courante: true,
    electricite: true,
    parking: true,
    jardin: true,
    meuble: true,
    climatisation: true,
    gardien: true,
    photos: [],
    created_at: '2024-11-01T10:00:00Z',
    updated_at: '2024-11-15T14:30:00Z'
  },
  {
    id: 2,
    titre: 'Appartement luxueux au centre-ville',
    description: 'Superbe appartement de 3 chambres avec vue panoramique sur la ville. Immeuble sécurisé avec gardien 24h/24, parking souterrain. Proche des commerces et transports.',
    type_bien: 'appartement',
    type_bien_display: 'Appartement',
    prix_mensuel: '2500',
    devise: "USD" as const,
    garantie: '5000',
    superficie: '180',
    nombre_chambres: 3,
    nombre_salles_bain: 2,
    nombre_pieces: 6,
    ville: 'Kinshasa',
    quartier: 'Limete',
    commune: 'Limete',
    adresse: '45 Boulevard du 30 Juin',
    latitude: '-4.3320',
    longitude: '15.3475',
    statut_validation: 'valide',
    statut_validation_display: 'Validé',
    statut_location: 'disponible',
    statut_location_display: 'Disponible',
    proprietaire: mockUsers[1],
    eau_courante: true,
    electricite: true,
    parking: true,
    jardin: false,
    meuble: true,
    climatisation: true,
    gardien: true,
    photos: [],
    created_at: '2024-11-05T10:00:00Z',
    updated_at: '2024-11-20T09:15:00Z'
  },
  {
    id: 3,
    titre: 'Studio meublé pour jeune professionnel',
    description: 'Studio moderne entièrement meublé, idéal pour jeune professionnel. Cuisine américaine équipée, salle de bain moderne. Quartier calme et sécurisé.',
    type_bien: 'studio',
    type_bien_display: 'Studio',
    prix_mensuel: '800',
    devise: "CDF" as const,
    garantie: '1600',
    superficie: '45',
    nombre_chambres: 1,
    nombre_salles_bain: 1,
    nombre_pieces: 2,
    ville: 'Kinshasa',
    quartier: 'Bandalungwa',
    commune: 'Bandalungwa',
    adresse: '78 Rue des Palmiers',
    latitude: '-4.3510',
    longitude: '15.2895',
    statut_validation: 'valide',
    statut_validation_display: 'Validé',
    statut_location: 'disponible',
    statut_location_display: 'Disponible',
    proprietaire: mockUsers[1],
    eau_courante: true,
    electricite: true,
    parking: false,
    jardin: false,
    meuble: true,
    climatisation: true,
    gardien: false,
    photos: [],
    created_at: '2024-11-10T10:00:00Z',
    updated_at: '2024-11-25T11:45:00Z'
  },
  {
    id: 4,
    titre: 'Maison familiale avec grand jardin',
    description: 'Belle maison familiale de 4 chambres avec un grand jardin arboré. Parfait pour une famille avec enfants. Quartier résidentiel calme, proche des écoles.',
    type_bien: 'maison',
    type_bien_display: 'Maison',
    prix_mensuel: '3200',
    devise: "USD" as const,
    garantie: '6400',
    superficie: '280',
    nombre_chambres: 4,
    nombre_salles_bain: 3,
    nombre_pieces: 8,
    ville: 'Lubumbashi',
    quartier: 'Golf',
    commune: 'Lubumbashi',
    adresse: '12 Avenue des Orangers',
    latitude: '-11.6647',
    longitude: '27.4794',
    statut_validation: 'valide',
    statut_validation_display: 'Validé',
    statut_location: 'disponible',
    statut_location_display: 'Disponible',
    proprietaire: mockUsers[1],
    eau_courante: true,
    electricite: true,
    parking: true,
    jardin: true,
    meuble: false,
    climatisation: false,
    gardien: true,
    photos: [],
    created_at: '2024-11-12T10:00:00Z',
    updated_at: '2024-11-28T16:20:00Z'
  },
  {
    id: 5,
    titre: 'Duplex moderne avec terrasse',
    description: 'Magnifique duplex de standing avec grande terrasse panoramique. 4 chambres spacieuses, 2 salons, cuisine moderne. Immeuble récent avec ascenseur.',
    type_bien: 'duplex',
    type_bien_display: 'Duplex',
    prix_mensuel: '4500',
    devise: "USD" as const,
    garantie: '9000',
    superficie: '320',
    nombre_chambres: 4,
    nombre_salles_bain: 3,
    nombre_pieces: 10,
    ville: 'Kinshasa',
    quartier: 'Ngaliema',
    commune: 'Ngaliema',
    adresse: '234 Avenue de la Libération',
    latitude: '-4.3225',
    longitude: '15.2550',
    statut_validation: 'valide',
    statut_validation_display: 'Validé',
    statut_location: 'disponible',
    statut_location_display: 'Disponible',
    proprietaire: mockUsers[1],
    eau_courante: true,
    electricite: true,
    parking: true,
    jardin: false,
    meuble: true,
    climatisation: true,
    gardien: true,
    photos: [],
    created_at: '2024-11-15T10:00:00Z',
    updated_at: '2024-12-01T10:00:00Z'
  },
  {
    id: 6,
    titre: 'Appartement économique bien situé',
    description: 'Appartement de 2 chambres, idéal pour petit budget. Bien situé proche des transports et commerces. Eau et électricité garantis.',
    type_bien: 'appartement',
    type_bien_display: 'Appartement',
    prix_mensuel: '600',
    devise: "USD" as const,
    garantie: '1200',
    superficie: '65',
    nombre_chambres: 2,
    nombre_salles_bain: 1,
    nombre_pieces: 4,
    ville: 'Goma',
    quartier: 'Himbi',
    commune: 'Goma',
    adresse: '56 Rue du Lac',
    latitude: '-1.6777',
    longitude: '29.2285',
    statut_validation: 'valide',
    statut_validation_display: 'Validé',
    statut_location: 'disponible',
    statut_location_display: 'Disponible',
    proprietaire: mockUsers[1],
    eau_courante: true,
    electricite: true,
    parking: false,
    jardin: false,
    meuble: false,
    climatisation: false,
    gardien: false,
    photos: [],
    created_at: '2024-11-18T10:00:00Z',
    updated_at: '2024-12-02T08:30:00Z'
  }
];

const mockDemandesVisite: DemandeVisite[] = [
  {
    id: 1,
    client: mockUsers[0],
    bien: 1,
    bien_detail: mockBiens[0] as BienList,
    date_souhaitee: '2024-12-10',
    heure_souhaitee: '10:00',
    message: 'Je souhaite visiter cette villa le matin de préférence.',
    statut: 'acceptee',
    statut_display: 'Acceptée',
    traitee_par: 3,
    traitee_par_detail: mockUsers[2],
    created_at: '2024-12-01T14:00:00Z'
  },
  {
    id: 2,
    client: mockUsers[0],
    bien: 2,
    bien_detail: mockBiens[1] as BienList,
    date_souhaitee: '2024-12-12',
    heure_souhaitee: '14:30',
    message: 'Disponible uniquement les après-midi.',
    statut: 'en_attente',
    statut_display: 'En attente',
    created_at: '2024-12-02T09:30:00Z'
  }
];

const mockVisites: Visite[] = [
  {
    id: 1,
    demande: 1,
    demande_detail: mockDemandesVisite[0],
    agent: 4,
    agent_detail: mockUsers[3],
    commissionnaire: 3,
    commissionnaire_detail: mockUsers[2],
    date_visite: '2024-12-10',
    heure_visite: '10:00',
    statut: 'planifiee',
    statut_display: 'Planifiée',
    created_at: '2024-12-02T10:00:00Z',
    updated_at: '2024-12-02T10:00:00Z'
  },
  {
    id: 2,
    demande: 1,
    demande_detail: mockDemandesVisite[0],
    agent: 4,
    agent_detail: mockUsers[3],
    commissionnaire: 3,
    commissionnaire_detail: mockUsers[2],
    date_visite: '2024-11-28',
    heure_visite: '14:00',
    statut: 'terminee',
    statut_display: 'Terminée',
    created_at: '2024-11-25T10:00:00Z',
    updated_at: '2024-11-28T16:00:00Z'
  },
  {
    id: 3,
    demande: 1,
    demande_detail: mockDemandesVisite[0],
    agent: 4,
    agent_detail: mockUsers[3],
    commissionnaire: 3,
    commissionnaire_detail: mockUsers[2],
    date_visite: '2024-11-20',
    heure_visite: '10:30',
    statut: 'terminee',
    statut_display: 'Terminée',
    created_at: '2024-11-18T10:00:00Z',
    updated_at: '2024-11-20T12:00:00Z'
  }
];

const mockChatRooms: ChatRoom[] = [
  {
    id: 1,
    demande_visite: 1,
    client: 1,
    client_detail: mockUsers[0],
    commissionnaire: 3,
    commissionnaire_detail: mockUsers[2],
    agent: 4,
    agent_detail: mockUsers[3],
    is_active: true,
    last_message: 'La visite est confirmée pour demain à 10h.',
    unread_count: 2,
    created_at: '2024-12-02T10:00:00Z',
    updated_at: '2024-12-05T08:00:00Z'
  }
];

const mockMessages: Message[] = [
  {
    id: 1,
    chatroom: 1,
    sender: 3,
    sender_detail: mockUsers[2],
    content: 'Bonjour, votre demande de visite a été acceptée.',
    is_read: true,
    created_at: '2024-12-02T10:05:00Z'
  },
  {
    id: 2,
    chatroom: 1,
    sender: 1,
    sender_detail: mockUsers[0],
    content: 'Merci beaucoup ! À quelle heure exactement ?',
    is_read: true,
    created_at: '2024-12-02T10:10:00Z'
  },
  {
    id: 3,
    chatroom: 1,
    sender: 3,
    sender_detail: mockUsers[2],
    content: 'La visite est confirmée pour demain à 10h.',
    is_read: false,
    created_at: '2024-12-05T08:00:00Z'
  }
];

const mockRapports: RapportVisite[] = [
  {
    id: 1,
    visite: 2,
    agent: 4,
    agent_detail: mockUsers[3],
    etat_general: 'tres_interessant',
    etat_general_display: 'Tres interessant',
    conformite_annonce: true,
    etat_electricite: 'Excellent - installation recente',
    etat_plomberie: 'Bon etat - aucune fuite detectee',
    etat_peinture: 'Peinture recente, couleurs neutres',
    etat_sols: 'Carrelage en bon etat',
    etat_fenetres: 'Double vitrage, bon etat',
    etat_portes: 'Portes en bois massif, excellent etat',
    accessibilite: 'Acces facile, parking disponible',
    environnement: 'Quartier calme et securise',
    points_positifs: 'Grande superficie, bien entretenu, quartier agreable',
    points_negatifs: 'Legere humidite dans une chambre',
    recommandations: 'Traiter le probleme d\'humidite avant location',
    commentaires: 'Bien correspondant a l\'annonce, client tres interesse',
    client_interesse: true,
    created_at: '2024-11-28T16:00:00Z',
    updated_at: '2024-11-28T16:00:00Z'
  },
  {
    id: 2,
    visite: 3,
    agent: 4,
    agent_detail: mockUsers[3],
    etat_general: 'interessant',
    etat_general_display: 'Interessant',
    conformite_annonce: true,
    etat_electricite: 'Bon etat',
    etat_plomberie: 'Correct',
    etat_peinture: 'A rafraichir',
    etat_sols: 'Usure normale',
    etat_fenetres: 'Simple vitrage',
    etat_portes: 'Bon etat',
    accessibilite: 'Escaliers - 2eme etage sans ascenseur',
    environnement: 'Proche commerces et transports',
    points_positifs: 'Emplacement ideal, lumineux',
    points_negatifs: 'Absence d\'ascenseur, peinture a refaire',
    recommandations: 'Negocier le prix vu les travaux necessaires',
    commentaires: 'Client interesse mais souhaite negocier',
    client_interesse: true,
    created_at: '2024-11-20T12:00:00Z',
    updated_at: '2024-11-20T12:00:00Z'
  }
];

const mockNotifications: Notification[] = [
  {
    id: 1,
    type_notification: 'demande_acceptee',
    type_display: 'Demande acceptée',
    titre: 'Votre demande de visite a été acceptée',
    message: 'Votre demande de visite pour "Villa moderne avec piscine à Gombe" a été acceptée.',
    is_read: false,
    data: { demande_id: 1, bien_id: 1 },
    created_at: '2024-12-05T08:00:00Z'
  },
  {
    id: 2,
    type_notification: 'visite_assignee',
    type_display: 'Visite assignée',
    titre: 'Un agent a été assigné à votre visite',
    message: 'Alice Lumumba sera votre guide pour la visite.',
    is_read: true,
    data: { visite_id: 1, agent_id: 4 },
    created_at: '2024-12-04T15:30:00Z'
  },
  {
    id: 3,
    type_notification: 'nouveau_message',
    type_display: 'Nouveau message',
    titre: 'Nouveau message dans votre conversation',
    message: 'Paul Mutombo vous a envoyé un message.',
    is_read: false,
    data: { chatroom_id: 1 },
    created_at: '2024-12-05T08:00:00Z'
  }
];

export const mockData = {
  users: mockUsers,
  biens: mockBiens,
  demandesVisite: mockDemandesVisite,
  visites: mockVisites,
  chatRooms: mockChatRooms,
  messages: mockMessages,
  notifications: mockNotifications,
  rapports: mockRapports
};

export function paginateResults<T>(items: T[], page = 1, pageSize = 10): PaginatedResponse<T> {
  const start = (page - 1) * pageSize;
  const end = start + pageSize;
  const results = items.slice(start, end);
  
  return {
    count: items.length,
    next: end < items.length ? `?page=${page + 1}` : null,
    previous: page > 1 ? `?page=${page - 1}` : null,
    results
  };
}
